name: RMN Mechancial
favicon: null
layout_spectrum: 0.26076
typography_spectrum: 0.49139
title: RMN Mechanical Co. Inc.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ed1c24'
    - '#2e3192'
    - '#ffffff'
    - '#000000'
    - '#cbac4e'
  brandStrength: 0.19192703068256378
  lightness: 0.11767351464368403
  saturation: 0.0642477204091847
  rhythmicContrast: 0.8812280090060085
purpose: []
