name: RMN Mechancial
favicon: null
layout_spectrum: 0.027593747479841113
typography_spectrum: 0.2555294637568295
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.19192703068256378
  lightness: 0.11767351464368403
  saturation: 0.0642477204091847
  rhythmicContrast: 0.8812280090060085
purpose: []
